### ISSUE TITLE
Validation & Exception throwing

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#3]
Context: https://github.com/vaizard/glued-skeleton/blob/c0a7e9dd9d5809daa4bc7d3b9db6b62370030591/glued/Core/Classes/Auth.php#L28

- We should have validators definitions somewhere neatly tucked away, so that we don't repeat stuff such as `v::intVal()->positive()->between(0, 4294967295)` gazillion times. Where do we put those? Some abstract class that'll be extended by other classes? Container? Hmm?
- It makes sense to throw exceptions when validation fails, right? (just kill stuff right where things go awkward)
- If answer to above is yes, then: typing out all the use Slim\Exception\* things is a nightmare and we should tuck things away. Again some abstract class?

**Comment by killua-eu** [comment]
I still hate the above. At first, I wanted to export validation to a middleware and just attach it. That might still be a good idea. Would then make sense to add a rbac middleware to deal with permissions. Buuut, what's missing out is dealing with errors (i.e. user not found in database, return 404) ... Which would get the $request completely out of the constructor, which would be a lovely thing.

**Comment by berkas1** [comment]
" so that we don't repeat stuff such as" this is a terrible terrible idea... Creating any class to make calls to other methods smaller in size reduces the readability of the code,messes up the code and makes it harder for the IDE to live a peaceful life. 

"It makes sense to throw exceptions when validation fails, right?" depends on the application architecture... I'll take a look at this within few days... Or we can discuss it on Thursday

**Comment by killua-eu** [comment]
resolved / see README.md
