### ISSUE TITLE
Glued skeleton requires mod_php

### ISSUE THREAD

**Issue by zelitomas** [vaizard/glued-skeleton#38]
2 solutions: 
 * Resolve ;)
 * Correctly document

**Comment by killua-eu** [comment]
maybe just move https://github.com/vaizard/glued-skeleton/blob/master/public/.htaccess#L14 to ini_set in index.php?

**Comment by killua-eu** [comment]
@zelitomas , could you retry now again? I think fedora defaults to the event mpm, co just comment out the mod_php in /etc/httpd as per chapter 6 https://blog.remirepo.net/post/2017/11/17/Fedora-27-changes-in-http-and-php but in reverse. Not sure if there isnt something else that will break due to not using the mod_php (a bit worried about the $_SERVER superglobals) .. please kindly review http://localhost/core/admin/phpinfo and just copy/paste or screenshot what you got under $_SERVER.

**Comment by killua-eu** [comment]
closed due to inactivity.
